# Generated by Django 5.1.6 on 2025-02-14 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TEMPORADA', 'Temporada'), ('BONO10', 'Bono 10 Entradas')], max_length=20, verbose_name='Tipo de Membresía')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('restantes', models.PositiveIntegerField(default=0, verbose_name='Entradas restantes')),
                ('activo', models.BooleanField(default=True, verbose_name='Membresía activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acceso')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membresia', verbose_name='Membresía')),
                ('validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
        ),
    ]
