# Generated by Django 5.1.6 on 2025-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias'),
        ),
    ]
